version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk
          
  elasticsearch:
      #build: elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
      # volumes:
    #  - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
        #environment:
        #ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    environment:
          - discovery.type=single-node

  logstash:
      #build: logstash/
    image: docker.elastic.co/logstash/logstash:5.6.3
    #volumes:
    #  - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

        #  kibana:
        #    build: kibana/
        #    volumes:
        #      - ./kibana/config/:/usr/share/kibana/config
        #    ports:
        #      - "5601:5601"
        #    networks:
        #      - elk
        #    depends_on:
        #      - elasticsearch
        #
networks:

  elk:
    driver: bridge
